### ISSUE TITLE
Live Server Query Returns Wrong Half-Life Version for DOD

### ISSUE THREAD

**Issue by Drek282** [Drek282/ps_dod#1]
> You need to set that log source to the folder where the logs for your game server are located. something like hlds\dod\logs

Awesome, so my issue was I was refering to a specific file, "psychostats.log" when I should have just put C:/Users/Vonaducci/Server/hldsdod/dod/logs

Now that I have it working just a few more questions:

First question: Is psychostats supposed to actively run and monitor the server or do I just schedule stats.pl to run once a day with windows task scheduler, kind of like how awards.pl works in hlstatsx? I ask because when I ran it, it scanned my logs, added all the information to the database, and then closed (I'm assuming that's the intended functionality). 

I wasn't able to get the live server view to work either until I commented out line 208 of halflife.php
![liveserveradderror](https://github.com/Drek282/PsychoStats/assets/145424300/507aa15a-1a7c-4694-8543-75b829151c2c)

It works after I comment out line 208:
$this->data['appid']			= $this->_getbyte() | ($this->_getbyte() << 8);

, but it causes the live server view to look like:
![slightlyglitched](https://github.com/Drek282/PsychoStats/assets/145424300/48774653-5910-444e-b090-c4f6b70c23fa)

Is there anyway to fix that or is that how it's supposed to look?

_Originally posted by @Vonaducci in https://github.com/Drek282/PsychoStats/issues/91#issuecomment-1835117363_

**Comment by Drek282** [comment]
The basic problem here is that the function that is supposed to return the Half-Life version is returning the wrong version.  My guess is this has to do with the recent 25th Anni update, and this is broken across all the modules.  I'm working on a fix that will work for HLDS, but I'm uncertain whether it will work for SRCDS, and I currently have no way of testing it.

**Comment by Drek282** [comment]
It appears that the query library we use is now mostly broken.  I expected this.  This is now in the todo list.

**Comment by Drek282** [comment]
I think the basic issue is that PS is still using the old query format, which was deprecated, and has now been completely removed.  I am going to be looking at using xPaw's query library.  I have no ETA on when I will have a working version.

**Comment by Rosenstein** [comment]
@Vonaducci , I've made some progress in regard to this issue. 
It could be fixed Soon™.

**Comment by Drek282** [comment]
@Rosenstein has done a complete end run around me on this one.  It's now his baby.  :)

**Comment by Rosenstein** [comment]
Just FYI, right HL version is being reported, it is by server design.
@Drek282

**Comment by Drek282** [comment]
Great, that's good to know.
