### ISSUE TITLE
Weapon Stat Anomalies

### ISSUE THREAD

**Issue by Vonaducci** [Drek282/ps_dod#2]
There seems to be some issues recording accurate weapon statistics for Day of Defeat 1.3.

For every weapon with effected missing stats, there exists an equivalent duplicate tracking the missing stats. For example:

The weapon called "30cal" has recorded 1,056 kills, but has only achieved 1 headshot, even with bots, that's statistically impossible. They aim erratically (their aim is entirely inconsistent and goes everywhere) and they have a much higher chance than 0.09% to hit a headshot with the .30 cal. The total damage done by the weapon named "30cal" is 933, meaning for each player killed, the killed player received on average 0.88 damage (936 damage / 1,056 kills = 0.88 average damage per death to the 30 cal.). A duplicate weapon called ".30 cal" has recorded 0 kills, yet it managed to get 187 headshots and did 115.8k damage (utterly amazing for 0 kills). This seems to be where the actual headshot and damage statistics went for the 30 cal. If I redo the previous calculation with those damage stats, we get an average 109 damage dealt for each kill by the 30 cal (115,800 damage / 1,056 kills = 109 damage per kill), a much more reasonable and realistic statistic for the 30 cal. 

The following weapons seem to have been effected by this bug (not an exhaustive list):
German Stick Grenade
US Frag Grenade
British Mills Bomb
StG-44
Springfield Rifle
Garand Butt
Panzerschrek
Scoped FG-42
M1 Carbine
K98 Bayonet
British Knife
American Knife
Kar-98
30 Cal
StG-44
Lee-Enfield bayonet
PIAT

Some weapons don't even have a duplicate and they still have no damage done: for example, the mortar.

I have included a screenshot of the weapons stats anomalies I'm talking about:
![psychostatsweaponanomalies](https://github.com/Drek282/ps_dod/assets/145424300/b4f9b6d7-a149-4d18-91b6-d464f6c7d335)

**Comment by Drek282** [comment]
Can you please zip up and send me a batch of logs from your server?  I think I may have an idea what is going on.

**Comment by Drek282** [comment]
Just to be perfectly clear.  I *can't* do anything with this until I have some  logs to work with.  I don't need GB worth, but a few MB of them would be ideal.

**Comment by Drek282** [comment]
I think what may be happening is that whatever bot plugin you are using is using different tags for weapon logging.

**Comment by Drek282** [comment]
Ok, I just ran a test using the logs you sent me @Vonaducci, and there were 0 duplicated weapons.  I know you or someone you work with, has modified the PS software at times.  I would suggest you delete your files, download the files again from the repo (both the base and the dod module), delete and recreate the database, and run your stats again.

edit:  It is also clear that, with most weapons, the bots don't aim for the head.  That isn't an issue with the stats.

edit again:  There is a reason why the bots don't aim for the head.  DoD is a high weapon damage mod.  You don't need a headshot to have a one shot kill.  Not only that, but the head might actually be the only hit location with an armour rating.

**Comment by Drek282** [comment]
If you experience the same issues with clean updated files from the GitHub repos, I will require an admin login to look at your settings to see if I can duplicate the issue.

**Comment by Drek282** [comment]
If I were to hazard a guess, I would  say someone has tried to add new weapons to the weapon list in the ACP, and done it incorrectly.  You shouldn't even need to do it.  All the weapons that appear in the stats should appear there.  If you want to modify weapon names, and such, you should do that with the entries that are already in the list.

**Comment by Drek282** [comment]
This issue is closed for now.  It will be reopened if I am able to recreate the issue and it isn't as I suspect, a matter of weapons being added to the ACP when they should not have been.
